### PR TITLE
Publish workflow: deploy images first

### PR DESCRIPTION
**Pull request by tidoust**
Images under the "images" folder were not published to GitHub Pages, resulting in broken links in the spec. This partly explains failure to publish to /TR (see #298).

In addition, images that are referenced by the WebCodecs spec need to be published to Github Pages before publication to /TR occurs, since publication to /TR makes a copy of the image. This update makes the job that takes care of publishing specs to /TR depend on the job that publishes the images.

The job that publishes the images is similar to the one used to deploy samples.

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 9, 2021, 3:52 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.

:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwebcodecs%2Fd64137cb72f5999a0f1b9a9058f6f91141aed173%2Findex.src.html&md-warning=not%20ready)

```
Error running preprocessor, returned code: 1.
Traceback (most recent call last):
  File "/sites/api.csswg.org/bikeshed/bikeshed.py", line 6, in 
    cli.main()
  File "/sites/api.csswg.org/bikeshed/bikeshed/cli.py", line 466, in main
    handleSpec(options, extras)
  File "/sites/api.csswg.org/bikeshed/bikeshed/cli.py", line 515, in handleSpec
    lineNumbers=options.lineNumbers,
  File "/sites/api.csswg.org/bikeshed/bikeshed/Spec.py", line 61, in __init__
    self.inputSource = InputSource(inputFilename, chroot=constants.chroot)
  File "/sites/api.csswg.org/bikeshed/bikeshed/InputSource.py", line 51, in __new__
    return UrlInputSource(sourceName, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'chroot'
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/webcodecs%23328.)._
</details>

### CODE REVIEW

**Comment by tidoust** [comment]
Argh, this approach is not entirely correct in practice: the workflow also runs on pull requests (to run tests) and thus the job I added deploys images on PR events too... In effect, it already deployed the images folder https://github.com/w3c/webcodecs/commit/b6dfb08a49a23567df02e516a91b86a7da66e539 even though this PR has not been merged yet... I'll push an update.

**Comment by tidoust** [comment]
That works better but I now realize that I got confused because the broken link actually exists in the source of the spec itself, as it links to `planar-interleaved-layout.svg` instead of `planar-interleaved.svg`.

I'll fix that as well but, more importantly, I believe that there is no need to couple publication of images to GitHub Pages and publication to /TR after all: publication to /TR should start from the `main` branch where the images are readily available. It failed to detect the image because the reference was incorrect, not because the image had not been published to GitHub Pages as I initially assumed.

Anyway, we still need to add a job to take care of images but that job can live on its own. I'll update the PR accordingly.

**Review by dalecurtis — APPROVED** [review]
Thanks!

**Review by tguilbert-google — APPROVED** [review]
Thanks for making these changes!

**Pull request merged**
