### PR TITLE
[WebCodecs] Fix markup for notes within lists

### PR DESCRIPTION
**Pull request by tidoust**
A `<div>` cannot appear within a `<dl>`. Bikeshed used to automatically tie notes with the previous `<dd>` in a list but no longer does that, and generated HTML is now invalid.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/477.html" title="Last updated on May 4, 2022, 11:47 AM UTC (5325113)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/477/34e21cb...5325113.html" title="Last updated on May 4, 2022, 11:47 AM UTC (5325113)">Diff</a>

### CODE REVIEW

**Comment by tidoust** [comment]
Note CI test failure on OPUS spec is expected. Fixed by #476.

**Comment by chcunningham** [comment]
Thanks @tidoust.  Looks like the opus check is still failing. I wasn't able to quickly determine the cause. Did you miss one?

**Comment by chcunningham** [comment]
Thanks @tidoust.  Looks like the opus check is still failing. I wasn't able to quickly determine the cause. Did you miss one?

**Comment by padenot** [comment]
Maybe it simply needs to be rebased.

**Comment by tidoust** [comment]
> Maybe it simply needs to be rebased.

Yes, CI tests start from the state of the repo at the time the PR was made (and thus could not see fix in #476). I rebased the PR.

**Comment by padenot** [comment]
Thanks for rebasing, merging now.

**Pull request merged**
