### PR TITLE
Add SVC modes and metadata

### LINKED ISSUE #85: Dynamic dropping/enabling of layers for SVC
This is done in webrtc with vp9 by setting target bitrate to 0 for the layer to be disabled, and it can be done anywhere in stream and without key frame. Is this feature supported for SVC?

### PR DESCRIPTION
**Pull request by chcunningham**
Adds VideoEncoderConfig.scalabilityMode to configure SVC encoding. 

Adds Encoded*ChunkMetadata interfaces to encoder output callbacks where chunk metadata is provided to describe SVC (currently just temporalLayerId) alognside the *DecodingConfig. Additional metadata fields would be added later.

Fixes #85 #40 #9

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/pull/187.html" title="Last updated on May 21, 2021, 5:38 AM UTC (636611f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webcodecs/187/7a0a448...636611f.html" title="Last updated on May 21, 2021, 5:38 AM UTC (636611f)">Diff</a>

### CODE REVIEW

**Comment by chcunningham** [comment]
@aboba @padenot - not quite done with this yet, but uploading for discussion. I'll send new commits tomorrow that break out the metadata dictionaries into their own section and offer more description about their members.

**Comment by chcunningham** [comment]
Note that this is not intended to address #161 or #182. I expect we may provide a separate mechanism for mutable metadata to address those.

Here, "metadata" refers to an encoder output. It describes a chunk, but it is intentionally not part of the chunk interface, as I want to avoid folks thinking that they need to describe various SVC metadata when giving chunks to the decoder (the only requirement when feeding SVC to the decoder is that you do so in decode order).

**Review by aboba — COMMENTED** [review]
This PR only includes the TID for metadata, not the other things discussed in https://docs.google.com/document/d/1O6kxAQPLWhCRHkH-6zutcqEUOUWRS6NFM2CQAvi1VTg/   Is this to focus on the things required for H.264/AVC with temporal scalability?  Wondering if it would make sense to put it all in now.

**Comment by chcunningham** [comment]
> This PR only includes the TID for metadata, not the other things discussed in https://docs.google.com/document/d/1O6kxAQPLWhCRHkH-6zutcqEUOUWRS6NFM2CQAvi1VTg/ Is this to focus on the things required for H.264/AVC with temporal scalability? Wondering if it would make sense to put it all in now.

That's right (focus on H.264). I will send a follow up PR shortly that adds the other fields. My aim is to prioritize this one, as it includes the breaking changes for the encoder output callback interface, and split off the less urgent discussion of the other metadata pieces.

**Review by aboba — APPROVED** [review]

**Comment by chcunningham** [comment]
Editors call: interface changes LGTM. Defer to @aboba on review of SVC particulars

**Comment by chcunningham** [comment]
Latest just fills in the algo steps needed to provide the metadata as previously discussed. Lets run through it quickly on tomorrows call.

**Comment by chcunningham** [comment]
Editors call: LGTM, merge it

**Pull request merged**
